name: Tests

on: [ push, pull_request ]

jobs:
    quality:
        name: Quality
        runs-on: ubuntu-latest


        strategy:
            matrix:
                php: [ '7.2', '7.4' ]


        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    coverage: "none"
                    extensions: "json,openssl,mbstring,xml,ctype,iconv,intl"
                    ini-values: "memory_limit=-1"
                    php-version: "${{ matrix.php }}"
                    tools: composer, prestissimo

            -   name: Determine composer cache directory
                id: composer-cache
                run: echo "::set-output name=directory::$(composer config cache-dir)"

            -   name: Cache composer dependencies
                uses: actions/cache@v1
                with:
                    path: ${{ steps.composer-cache.outputs.directory }}
                    key: ${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ matrix.php }}-composer-

            -   name: Install Composer dependencies
                run: |
                    composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader --ansi

            -   name: Pre-conditions
                run: |
                    vendor/bin/check-syntax-php.sh
                    vendor/simplesamlphp/simplesamlphp-test-framework/bin/check-syntax-json.sh
                    vendor/simplesamlphp/simplesamlphp-test-framework/bin/check-syntax-xml.sh
                    vendor/simplesamlphp/simplesamlphp-test-framework/bin/check-syntax-yaml.sh

            -   name: Quality
                run: |
                    vendor/bin/security-checker security:check
                    vendor/bin/psalm
                    vendor/bin/psalter --issues=UnnecessaryVarAnnotation --dry-run
                    vendor/bin/phpcs


    integration:
        name: Integration
        runs-on: ubuntu-latest
        needs: [ quality ]

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    coverage: "pcov"
                    extensions: "json,openssl,mbstring,xml,ctype,iconv,intl"
                    ini-values: "memory_limit=-1"
                    php-version: "7.2"
                    tools: composer, prestissimo

            -   name: Determine composer cache directory
                id: composer-cache
                run: echo "::set-output name=directory::$(composer config cache-dir)"

            -   name: Cache composer dependencies
                uses: actions/cache@v1
                with:
                    path: ${{ steps.composer-cache.outputs.directory }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-composer-

            -   name: Install Composer dependencies
                run: |
                    composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader --ansi

            -   name: Tests
                run: |
                    vendor/bin/phpunit --no-coverage
                    vendor/bin/phpspec run

            -   name: Upload coverage results to Coveralls
                env:
                    COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: |
                    composer global require twinh/php-coveralls
                    vendor/bin/phpunit
                    php-coveralls --coverage_clover=build/logs/clover.xml -v
